name: Compress images
on: pull_request
jobs:
  build:
    name: calibreapp/webp-optimizer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1.0.0-alpha

      - name: Compress Images
        uses: calibreapp/webp-optimizer@v1.0.0-alpha
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: "80"
          pngQuality: "80"
          webpQuality: "80"
          ignorePaths: "node_modules/**,build,dist,public/images2/new/guest/**,android/**"
